#ifndef TCM_NL_H
#define TCM_NL_H

#define TCM_GENL_FAMILY_NAME "tcm"
#define TCM_GENL_MCGRP_HOOK_NAME "hook"
#define TCM_GENL_VERSION 1

enum tcm_genl_cmd {
  TCM_GENL_CMD_UNSPEC,
  TCM_GENL_CMD_FORK_RET_EVENT,
  TCM_GENL_CMD_FILE_EVENT,
  TCM_GENL_CMD_EXIT_EVENT,
  TCM_GENL_CMD_FILE_STATS_EVENT,
  __TCM_GENL_CMD_MAX,
};
#define TCM_GENL_CMD_MAX (__TCM_GENL_CMD_MAX - 1)

enum tcm_genl_op {
  TCM_GENL_OP_REGISTER,
  TCM_GENL_OP_GET_FILE_STATS,
  __TCM_GENL_OP_MAX,
};
#define TCM_GENL_OP_MAX (__TCM_GENL_OP_MAX - 1)

enum tcm_genl_attr {
  TCM_GENL_ATTR_UNSPEC,
  TCM_GENL_ATTR_PARENT_PID,
  TCM_GENL_ATTR_CHILD_PID,
  TCM_GENL_ATTR_PARENT_PATH,
  TCM_GENL_ATTR_CHILD_PATH,
  TCM_GENL_ATTR_FILE_PID,
  TCM_GENL_ATTR_FILE_FD,
  TCM_GENL_ATTR_FILE_PATH,
  TCM_GENL_ATTR_FILE_OPERATION,
  TCM_GENL_ATTR_EXIT_PID,
  TCM_GENL_ATTR_EXIT_CODE,
  TCM_GENL_ATTR_FILE_STATS_PID_TABLE_SIZE,
  TCM_GENL_ATTR_FILE_STATS_PID_ENTRY_COUNT,
  TCM_GENL_ATTR_FILE_STATS_FILE_ENTRY_COUNT,
  TCM_GENL_ATTR_FILE_STATS_TOP_PID_COUNT,
  TCM_GENL_ATTR_FILE_STATS_TOP_PIDS,
  TCM_GENL_ATTR_CLIENT_PID,
  __TCM_GENL_ATTR_MAX,
};
#define TCM_GENL_ATTR_MAX (__TCM_GENL_ATTR_MAX - 1)

enum tcm_genl_mcgrp {
  TCM_GENL_MCGRP_HOOK,
  __TCM_GENL_MCGRP_MAX,
};
#define TCM_GENL_MCGRP_MAX (__TCM_GENL_MCGRP_MAX - 1)

#endif /* TCM_NL_H */